### ISSUE TITLE
[PE-D][Tester B] No response when edit command is incomplete

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2113-W12-3/tp#122]
![image.png](https://raw.githubusercontent.com/cxc0418/ped/main/files/166ac17b-0251-4251-a264-56930ad0615f.png)

When executing edit 2, the application does not provide any feedback or error message. This could confuse users, as they are not informed about what parameters are missing or what went wrong.
Steps to Reproduce:
Run the application.
Enter the command edit2 (observe: correct error message is shown).
Enter the command edit 2 (observe: no feedback given).
Expected Behavior: An error message should be displayed, explaining that additional parameters are required to perform the edit.
Actual Behavior: The application does not respond, leaving the user without guidance

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: cxc0418/ped#1

**Comment by Hackin7** [comment]
Fixed in the linked PR

```
> edit 2
Index is out of bounds.
> edit 1
No related arguments were given to update the expense.
>
```
