### ISSUE TITLE
[PE-D][Tester B] No confirmation message after adding a recurring expense

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2113-W12-3/tp#136]
![image.png](https://raw.githubusercontent.com/cxc0418/ped/main/files/e3177170-e534-43ae-892d-c622109c82c5.png)

When a recurring expense is added using the add /recur command, the application does not display any feedback or confirmation message. This may confuse users, as they cannot be sure if the recurring expense was added correctly.
Steps to Reproduce:
Use the add /recur command to add a recurring expense (e.g., add /recur /price 10 /description phone bill /category utilities /frequency monthly).
Check that no confirmation message appears in the console.
Expected Behavior: A confirmation message should be displayed to indicate that the recurring expense was added successfully.
Actual Behavior: The application does not provide any feedback, leaving the user unsure if the operation was successful.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: cxc0418/ped#6

**Comment by Hackin7** [comment]
This links up with this issue https://github.com/AY2425S1-CS2113-W12-3/tp/issues/149. As such I'll be closing this specific issue first to clear duplicates, and we can reopen it as needed
