### ISSUE TITLE
[PE-D][Tester E] Delete command has some random errors

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2113-W12-3/tp#148]
![image.png](https://raw.githubusercontent.com/wahkia/ped/main/files/f550510c-9b8b-496d-96f2-db9f5f805ac5.png)

Delete error command sometimes throws an error but still deletes the line

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: wahkia/ped#4

**Comment by Progresst-8** [comment]
Should have been fixed by PR #171 #172 #173
