### ISSUE TITLE
[PE-D][Tester E] Incomplete examples for visualize command 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2113-W12-3/tp#161]
Shouldnt the Examples of the UG show valid ways of using the command? With the examples given, I can am only greeted with error messages.

![image.png](https://raw.githubusercontent.com/wahkia/ped/main/files/77c5499e-6f4b-4fb2-91e6-7ab92ff04cf7.png)

Error messages:

![image.png](https://raw.githubusercontent.com/wahkia/ped/main/files/96d7490c-8312-4e64-a39c-4ec7214058de.png)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: wahkia/ped#9

**Comment by KHsienKit** [comment]
![image](https://github.com/user-attachments/assets/9fea2de6-c153-41dd-8e86-2beeaa46a534)

It is stated in the UG that the visualiser only works for a range of 1080 days
