### ISSUE TITLE
Review comments on your DG

### ISSUE THREAD

**Issue by okkhoy** [AY2425S1-CS2113-W12-3/tp#86]
1. "The following diagram is an **inheritance diagram** for Command and its children classes" -- no such thing as an **inheritance diagram**
2. notation: activation bar appears to have no beginning and end
![image](https://github.com/user-attachments/assets/b2bf64da-6281-46a3-81c9-b0b31d9fa52d)
3. notation
![image](https://github.com/user-attachments/assets/5b96033f-3e2d-45fe-a054-58d1a8f4bb10)
4. In general, in your class diagrams, you can eliminate those methods that are not under the scope of discussion in the text that follows. e.g., you mention that `Expense` class has no notable methods, so this class diagram need not be so exhaustive. (prioritize comprehensible over comprehensive)
![image](https://github.com/user-attachments/assets/bf9b17db-406a-488e-b4d9-81cdb0f08f66)
5. Can abstract out all of this to "open data csv file for reading"; that way you will simplify the SD
![image](https://github.com/user-attachments/assets/031bd457-2f79-4f6a-894c-1826fb34ce19)
6. can be a SD on its own (how to handle recurring transactions), and probably more important than reading csv file above in the diagram
![image](https://github.com/user-attachments/assets/30a6ff37-5779-425c-8e35-276cb6825cbc)

**Comment by Hackin7** [comment]
I'll close this again as I feel most of it should have been settled in v2.0. Any new issues in DG a new issue should be created on Github


from what I've heard, arrowhead is a non issue according to the prof
